DROP SCHEMA IF EXISTS PROJECT;
CREATE SCHEMA IF NOT EXISTS PROJECT;
USE PROJECT;

CREATE TABLE IF NOT EXISTS USERS(
	ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(200),
    FIRSTNAME VARCHAR(200),
    UNIQUE(USERNAME),
    PRIMARY KEY(ID)
);
INSERT INTO USERS(USERNAME, PASSWORD, FIRSTNAME) VALUES("guest", MD5("1234"), "guest");